/**
 * Coordinates and tables for the short solver (`shortSolver.ts`).
 *
 * The search never touches a `CubeState` inside its loops: an object per node
 * would make it hundreds of times slower. Instead the parts of the state that
 * matter are packed into small integers — coordinates — and every turn is a
 * lookup in a table that says where a coordinate goes. A second family of
 * tables says how many turns, at least, separate a coordinate pair from the
 * goal; the search uses it to cut branches that cannot finish in time.
 *
 * ## The two phases and their coordinates
 *
 * Phase 1 brings the cube into the subgroup generated by
 * `U, D, R2, L2, F2, B2`: every corner and edge oriented, the four middle-layer
 * edges (FR, FL, BL, BR) somewhere in the middle layer. Its coordinates:
 *
 * - `twist` — orientations of the corners, 3^7 = 2187 values;
 * - `flip` — orientations of the edges, 2^11 = 2048 values;
 * - `slice` — which four slots the middle-layer edges occupy, C(12,4) = 495.
 *
 * The last corner and the last edge are not stored: the orientation sums of a
 * real cube fix them.
 *
 * Phase 2 finishes inside that subgroup with its ten turns. Its coordinates are
 * permutations only, orientation being solved already:
 *
 * - `cornerPerm` — the eight corners, 8! = 40320;
 * - `edgePerm` — the eight edges of U and D, 8! = 40320;
 * - `slicePerm` — the four middle-layer edges among themselves, 4! = 24.
 *
 * All of them are 0 on a solved cube, which is what makes "is this the goal"
 * a comparison with zero.
 *
 * ## Where the moves come from
 *
 * Not from a second copy of the turn definitions: every table here is built by
 * applying the engine's own turns (`moves.ts`) to a cube. The engine is the
 * single place a wrong turn could hide, and the short solver inherits its tests
 * instead of needing its own set of facts about the cube.
 *
 * ## Size and cost
 *
 * The tables take about 5.8 MB of memory and are computed on first use, in a
 * fraction of a second to about a second depending on the machine. Why they are
 * computed rather than shipped is argued in the pull request that introduced
 * them: shipping them would cost every visitor of `/solve` megabytes for a mode
 * most of them never open.
 */

import { CORNER_COUNT, EDGE_COUNT, SOLVED_CUBE } from "./state";
import { MOVES, applyMove } from "./moves";

export const MOVE_COUNT = MOVES.length;

/**
 * The ten turns of phase 2, as indices into `MOVES`:
 * `U U2 U' D D2 D' L2 R2 F2 B2`. Quarter turns of the side faces would undo
 * what phase 1 achieved, so phase 2 never uses them.
 */
export const PHASE2_MOVES: readonly number[] = Object.freeze([0, 1, 2, 3, 4, 5, 7, 10, 13, 16]);
export const PHASE2_MOVE_COUNT = PHASE2_MOVES.length;

export const TWIST_COUNT = 2187;
export const FLIP_COUNT = 2048;
export const SLICE_COUNT = 495;
export const CORNER_PERM_COUNT = 40320;
export const EDGE_PERM_COUNT = 40320;
export const SLICE_PERM_COUNT = 24;

/** The middle-layer edges are the last four in `EDGES`: FR, FL, BL, BR. */
const FIRST_SLICE_EDGE = 8;
const UD_EDGE_COUNT = 8;
const SLICE_EDGE_COUNT = 4;

/**
 * A cube as four flat arrays — the same numbers as `CubeState`, in the same
 * slot order, but mutable and cheap to copy. Used only while building tables
 * and when phase 1 hands over to phase 2.
 */
export interface RawCube {
  cp: Uint8Array;
  co: Uint8Array;
  ep: Uint8Array;
  eo: Uint8Array;
}

export function rawCube(): RawCube {
  const cube: RawCube = {
    cp: new Uint8Array(CORNER_COUNT),
    co: new Uint8Array(CORNER_COUNT),
    ep: new Uint8Array(EDGE_COUNT),
    eo: new Uint8Array(EDGE_COUNT),
  };
  for (let slot = 0; slot < CORNER_COUNT; slot++) cube.cp[slot] = slot;
  for (let slot = 0; slot < EDGE_COUNT; slot++) cube.ep[slot] = slot;
  return cube;
}

/** Each turn as the state it leaves on a solved cube — what composing with it means. */
const MOVE_CUBES = MOVES.map((move) => applyMove(SOLVED_CUBE, move));

/**
 * `into` becomes `from` followed by turn `move`. The arithmetic is the engine's
 * `compose`, spelled out on flat arrays; `into` and `from` must differ.
 */
export function applyRawMove(from: RawCube, move: number, into: RawCube): void {
  const turn = MOVE_CUBES[move];
  for (let slot = 0; slot < CORNER_COUNT; slot++) {
    const source = turn.cornerPermutation[slot];
    into.cp[slot] = from.cp[source];
    into.co[slot] = (from.co[source] + turn.cornerOrientation[slot]) % 3;
  }
  for (let slot = 0; slot < EDGE_COUNT; slot++) {
    const source = turn.edgePermutation[slot];
    into.ep[slot] = from.ep[source];
    into.eo[slot] = (from.eo[source] + turn.edgeOrientation[slot]) % 2;
  }
}

// --- Orientation coordinates -------------------------------------------------

export function twistOf(co: ArrayLike<number>): number {
  let twist = 0;
  for (let slot = 0; slot < CORNER_COUNT - 1; slot++) twist = twist * 3 + co[slot];
  return twist;
}

export function setTwist(twist: number, co: Uint8Array): void {
  let sum = 0;
  for (let slot = CORNER_COUNT - 2; slot >= 0; slot--) {
    co[slot] = twist % 3;
    sum += co[slot];
    twist = Math.floor(twist / 3);
  }
  co[CORNER_COUNT - 1] = (3 - (sum % 3)) % 3;
}

export function flipOf(eo: ArrayLike<number>): number {
  let flip = 0;
  for (let slot = 0; slot < EDGE_COUNT - 1; slot++) flip = flip * 2 + eo[slot];
  return flip;
}

export function setFlip(flip: number, eo: Uint8Array): void {
  let sum = 0;
  for (let slot = EDGE_COUNT - 2; slot >= 0; slot--) {
    eo[slot] = flip % 2;
    sum += eo[slot];
    flip = Math.floor(flip / 2);
  }
  eo[EDGE_COUNT - 1] = sum % 2;
}

// --- Middle-layer edge positions ----------------------------------------------

const BINOMIAL: readonly number[][] = Array.from({ length: EDGE_COUNT + 1 }, (_, n) =>
  Array.from({ length: SLICE_EDGE_COUNT + 2 }, (_, k) => {
    if (k > n) return 0;
    let value = 1;
    for (let i = 0; i < k; i++) value = (value * (n - i)) / (i + 1);
    return value;
  })
);

const choose = (n: number, k: number): number => (k > n ? 0 : BINOMIAL[n][k]);

/**
 * Which four slots hold middle-layer edges, as the rank of that set among all
 * C(12,4) sets. Their order among themselves is `slicePerm`'s business.
 */
export function sliceOf(ep: ArrayLike<number>): number {
  let slice = 0;
  let seen = 0;
  for (let slot = EDGE_COUNT - 1; slot >= 0; slot--) {
    if (ep[slot] >= FIRST_SLICE_EDGE) {
      slice += choose(EDGE_COUNT - 1 - slot, seen + 1);
      seen++;
    }
  }
  return slice;
}

/** Places the middle-layer edges by `slice`; the other edges fill the rest in order. */
export function setSlice(slice: number, ep: Uint8Array): void {
  let left = SLICE_EDGE_COUNT;
  const taken = new Array<boolean>(EDGE_COUNT).fill(false);
  for (let slot = 0; slot < EDGE_COUNT; slot++) {
    const step = choose(EDGE_COUNT - 1 - slot, left);
    if (left > 0 && slice - step >= 0) {
      ep[slot] = FIRST_SLICE_EDGE + SLICE_EDGE_COUNT - left;
      taken[slot] = true;
      slice -= step;
      left--;
    }
  }
  let other = 0;
  for (let slot = 0; slot < EDGE_COUNT; slot++) {
    if (!taken[slot]) ep[slot] = other++;
  }
}

// --- Permutations -------------------------------------------------------------

/**
 * Lehmer rank of `values[offset .. offset+length)`. Only the relative order of
 * the values counts, so edges 8–11 rank the same as 0–3 would. The identity
 * ranks 0.
 */
export function permutationRank(values: ArrayLike<number>, length: number, offset = 0): number {
  let rank = 0;
  for (let i = 0; i < length; i++) {
    const value = values[offset + i];
    let smaller = 0;
    for (let j = i + 1; j < length; j++) {
      if (values[offset + j] < value) smaller++;
    }
    rank = rank * (length - i) + smaller;
  }
  return rank;
}

const PERMUTATION_DIGITS = new Uint8Array(EDGE_COUNT);
const PERMUTATION_USED = new Uint8Array(EDGE_COUNT + 1);

/**
 * Inverse of `permutationRank`: writes the permutation of `base .. base+length`
 * into `into[offset ..]`.
 */
export function setPermutation(
  rank: number,
  length: number,
  into: Uint8Array,
  offset = 0,
  base = 0
): void {
  // Scratch space instead of fresh arrays: this runs 80 000 times per build.
  const digits = PERMUTATION_DIGITS;
  const used = PERMUTATION_USED;
  for (let i = length - 1; i >= 0; i--) {
    const radix = length - i;
    const digit = rank % radix;
    digits[i] = digit;
    rank = (rank - digit) / radix;
    used[i] = 0;
  }
  // Digit i picks the digit-th smallest value not yet placed.
  for (let i = 0; i < length; i++) {
    let skip = digits[i];
    let value = 0;
    while (used[value] === 1 || skip-- > 0) {
      value++;
      while (used[value] === 1) value++;
    }
    used[value] = 1;
    into[offset + i] = base + value;
  }
}

export const cornerPermOf = (cp: ArrayLike<number>): number =>
  permutationRank(cp, CORNER_COUNT);

/** Valid only inside the phase-2 subgroup, where slots 0–7 hold edges 0–7. */
export const edgePermOf = (ep: ArrayLike<number>): number => permutationRank(ep, UD_EDGE_COUNT);

/** Edges 8–11 among themselves, in slots 8–11. */
export const slicePermOf = (ep: ArrayLike<number>): number =>
  permutationRank(ep, SLICE_EDGE_COUNT, FIRST_SLICE_EDGE);

// --- Tables -------------------------------------------------------------------

export interface MoveTables {
  /** `twistMove[twist * 18 + move]` — the twist after that turn; same shape for the next two. */
  twistMove: Uint16Array;
  flipMove: Uint16Array;
  sliceMove: Uint16Array;
  /** `cornerPermMove[cornerPerm * 10 + i]` — after phase-2 turn `PHASE2_MOVES[i]`; same for the next two. */
  cornerPermMove: Uint16Array;
  edgePermMove: Uint16Array;
  slicePermMove: Uint16Array;
}

export interface PruningTables {
  /** Fewest turns to phase-1 goal for `slice * TWIST_COUNT + twist`, ignoring flip. */
  sliceTwist: Int8Array;
  /** Same for `slice * FLIP_COUNT + flip`, ignoring twist. */
  sliceFlip: Int8Array;
  /** Fewest phase-2 turns to solved for `cornerPerm * 24 + slicePerm`, ignoring edges. */
  cornerSlice: Int8Array;
  /** Same for `edgePerm * 24 + slicePerm`, ignoring corners. */
  edgeSlice: Int8Array;
}

export interface Tables extends MoveTables, PruningTables {}

function buildTable(
  size: number,
  moves: readonly number[],
  set: (coordinate: number, cube: RawCube) => void,
  read: (cube: RawCube) => number
): Uint16Array {
  const table = new Uint16Array(size * moves.length);
  const from = rawCube();
  const into = rawCube();
  for (let coordinate = 0; coordinate < size; coordinate++) {
    set(coordinate, from);
    for (let i = 0; i < moves.length; i++) {
      applyRawMove(from, moves[i], into);
      table[coordinate * moves.length + i] = read(into);
    }
  }
  return table;
}

const ALL_MOVES: readonly number[] = MOVES.map((_, index) => index);

export function buildMoveTables(): MoveTables {
  return {
    twistMove: buildTable(TWIST_COUNT, ALL_MOVES, (t, cube) => setTwist(t, cube.co), (cube) =>
      twistOf(cube.co)
    ),
    flipMove: buildTable(FLIP_COUNT, ALL_MOVES, (f, cube) => setFlip(f, cube.eo), (cube) =>
      flipOf(cube.eo)
    ),
    sliceMove: buildTable(SLICE_COUNT, ALL_MOVES, (s, cube) => setSlice(s, cube.ep), (cube) =>
      sliceOf(cube.ep)
    ),
    cornerPermMove: buildTable(
      CORNER_PERM_COUNT,
      PHASE2_MOVES,
      (p, cube) => setPermutation(p, CORNER_COUNT, cube.cp),
      (cube) => cornerPermOf(cube.cp)
    ),
    edgePermMove: buildTable(
      EDGE_PERM_COUNT,
      PHASE2_MOVES,
      (p, cube) => setPermutation(p, UD_EDGE_COUNT, cube.ep),
      (cube) => edgePermOf(cube.ep)
    ),
    slicePermMove: buildTable(
      SLICE_PERM_COUNT,
      PHASE2_MOVES,
      (p, cube) => setPermutation(p, SLICE_EDGE_COUNT, cube.ep, FIRST_SLICE_EDGE, FIRST_SLICE_EDGE),
      (cube) => slicePermOf(cube.ep)
    ),
  };
}

/**
 * Breadth-first distances from the goal over pairs of coordinates.
 *
 * Every entry is the exact distance in the space of the pair, which is never
 * more than the distance for the whole cube — that is what makes the table a
 * safe lower bound for the search.
 */
function buildPruning(
  outerSize: number,
  outerMove: Uint16Array,
  innerSize: number,
  innerMove: Uint16Array,
  moveCount: number
): Int8Array {
  const total = outerSize * innerSize;
  const table = new Int8Array(total).fill(-1);
  table[0] = 0;
  let filled = 1;
  for (let depth = 0; filled < total; depth++) {
    for (let index = 0; index < total; index++) {
      if (table[index] !== depth) continue;
      const outer = (index / innerSize) | 0;
      const inner = index - outer * innerSize;
      for (let move = 0; move < moveCount; move++) {
        const next =
          outerMove[outer * moveCount + move] * innerSize + innerMove[inner * moveCount + move];
        if (table[next] === -1) {
          table[next] = depth + 1;
          filled++;
        }
      }
    }
  }
  return table;
}

export function buildPruningTables(moves: MoveTables): PruningTables {
  return {
    sliceTwist: buildPruning(SLICE_COUNT, moves.sliceMove, TWIST_COUNT, moves.twistMove, MOVE_COUNT),
    sliceFlip: buildPruning(SLICE_COUNT, moves.sliceMove, FLIP_COUNT, moves.flipMove, MOVE_COUNT),
    cornerSlice: buildPruning(
      CORNER_PERM_COUNT,
      moves.cornerPermMove,
      SLICE_PERM_COUNT,
      moves.slicePermMove,
      PHASE2_MOVE_COUNT
    ),
    edgeSlice: buildPruning(
      EDGE_PERM_COUNT,
      moves.edgePermMove,
      SLICE_PERM_COUNT,
      moves.slicePermMove,
      PHASE2_MOVE_COUNT
    ),
  };
}

let cached: Tables | null = null;

/**
 * All tables, built on the first call and kept for the life of the module —
 * the page's worker, or one test file.
 */
export function getTables(): Tables {
  if (cached === null) {
    const moves = buildMoveTables();
    cached = { ...moves, ...buildPruningTables(moves) };
  }
  return cached;
}

/** Whether `getTables` has already paid for the tables. */
export function tablesReady(): boolean {
  return cached !== null;
}
